services:
  - type: web
    name: wirebase
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        value: ${SUPABASE_URL}
      - key: SUPABASE_KEY
        value: ${SUPABASE_KEY}
      - key: SUPABASE_SERVICE_KEY
        value: ${SUPABASE_SERVICE_KEY}
      - key: DATABASE_URL
        fromDatabase:
          name: wirebase-postgres
          property: connectionString

databases:
  - name: wirebase-postgres
    plan: free
    databaseName: wirebase
